// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.3
// source: peernode.proto

package peernode

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileProducer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash           string  `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Link           string  `protobuf:"bytes,2,opt,name=link,proto3" json:"link,omitempty"`
	Price          float32 `protobuf:"fixed32,3,opt,name=price,proto3" json:"price,omitempty"`
	PaymentAddress string  `protobuf:"bytes,4,opt,name=payment_address,json=paymentAddress,proto3" json:"payment_address,omitempty"`
}

func (x *FileProducer) Reset() {
	*x = FileProducer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_peernode_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileProducer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileProducer) ProtoMessage() {}

func (x *FileProducer) ProtoReflect() protoreflect.Message {
	mi := &file_peernode_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileProducer.ProtoReflect.Descriptor instead.
func (*FileProducer) Descriptor() ([]byte, []int) {
	return file_peernode_proto_rawDescGZIP(), []int{0}
}

func (x *FileProducer) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *FileProducer) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *FileProducer) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *FileProducer) GetPaymentAddress() string {
	if x != nil {
		return x.PaymentAddress
	}
	return ""
}

type FileHash struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash string `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (x *FileHash) Reset() {
	*x = FileHash{}
	if protoimpl.UnsafeEnabled {
		mi := &file_peernode_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileHash) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileHash) ProtoMessage() {}

func (x *FileHash) ProtoReflect() protoreflect.Message {
	mi := &file_peernode_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileHash.ProtoReflect.Descriptor instead.
func (*FileHash) Descriptor() ([]byte, []int) {
	return file_peernode_proto_rawDescGZIP(), []int{1}
}

func (x *FileHash) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type FileProducerList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Producers []*FileProducer `protobuf:"bytes,1,rep,name=producers,proto3" json:"producers,omitempty"`
}

func (x *FileProducerList) Reset() {
	*x = FileProducerList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_peernode_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileProducerList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileProducerList) ProtoMessage() {}

func (x *FileProducerList) ProtoReflect() protoreflect.Message {
	mi := &file_peernode_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileProducerList.ProtoReflect.Descriptor instead.
func (*FileProducerList) Descriptor() ([]byte, []int) {
	return file_peernode_proto_rawDescGZIP(), []int{2}
}

func (x *FileProducerList) GetProducers() []*FileProducer {
	if x != nil {
		return x.Producers
	}
	return nil
}

var File_peernode_proto protoreflect.FileDescriptor

var file_peernode_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x70, 0x65, 0x65, 0x72, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x70, 0x65, 0x65, 0x72, 0x6e, 0x6f, 0x64, 0x65, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x75, 0x0a, 0x0c, 0x46, 0x69, 0x6c, 0x65, 0x50,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x6c,
	0x69, 0x6e, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x12,
	0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05,
	0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74,
	0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e,
	0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x1e,
	0x0a, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x48, 0x61, 0x73, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61,
	0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x22, 0x48,
	0x0a, 0x10, 0x46, 0x69, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x34, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x65, 0x65, 0x72, 0x6e, 0x6f, 0x64, 0x65,
	0x2e, 0x46, 0x69, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x52, 0x09, 0x70,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x73, 0x32, 0x92, 0x01, 0x0a, 0x0d, 0x4d, 0x61, 0x72,
	0x6b, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3f, 0x0a, 0x0b, 0x41, 0x64,
	0x64, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x12, 0x16, 0x2e, 0x70, 0x65, 0x65, 0x72,
	0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65,
	0x72, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x0c, 0x47,
	0x65, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x73, 0x12, 0x12, 0x2e, 0x70, 0x65,
	0x65, 0x72, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x48, 0x61, 0x73, 0x68, 0x1a,
	0x1a, 0x2e, 0x70, 0x65, 0x65, 0x72, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x50,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x00, 0x42, 0x0c, 0x5a,
	0x0a, 0x2e, 0x2f, 0x70, 0x65, 0x65, 0x72, 0x6e, 0x6f, 0x64, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_peernode_proto_rawDescOnce sync.Once
	file_peernode_proto_rawDescData = file_peernode_proto_rawDesc
)

func file_peernode_proto_rawDescGZIP() []byte {
	file_peernode_proto_rawDescOnce.Do(func() {
		file_peernode_proto_rawDescData = protoimpl.X.CompressGZIP(file_peernode_proto_rawDescData)
	})
	return file_peernode_proto_rawDescData
}

var file_peernode_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_peernode_proto_goTypes = []interface{}{
	(*FileProducer)(nil),     // 0: peernode.FileProducer
	(*FileHash)(nil),         // 1: peernode.FileHash
	(*FileProducerList)(nil), // 2: peernode.FileProducerList
	(*emptypb.Empty)(nil),    // 3: google.protobuf.Empty
}
var file_peernode_proto_depIdxs = []int32{
	0, // 0: peernode.FileProducerList.producers:type_name -> peernode.FileProducer
	0, // 1: peernode.MarketService.AddProducer:input_type -> peernode.FileProducer
	1, // 2: peernode.MarketService.GetProducers:input_type -> peernode.FileHash
	3, // 3: peernode.MarketService.AddProducer:output_type -> google.protobuf.Empty
	2, // 4: peernode.MarketService.GetProducers:output_type -> peernode.FileProducerList
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_peernode_proto_init() }
func file_peernode_proto_init() {
	if File_peernode_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_peernode_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileProducer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_peernode_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileHash); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_peernode_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileProducerList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_peernode_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_peernode_proto_goTypes,
		DependencyIndexes: file_peernode_proto_depIdxs,
		MessageInfos:      file_peernode_proto_msgTypes,
	}.Build()
	File_peernode_proto = out.File
	file_peernode_proto_rawDesc = nil
	file_peernode_proto_goTypes = nil
	file_peernode_proto_depIdxs = nil
}
